# Generated by Django 2.2.6 on 2019-11-11 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20191020_2229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='book_name',
            new_name='books',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='member_name',
            new_name='member',
        ),
    ]
